### ISSUE TITLE
Can't setup WiFi and MQTT

### ISSUE THREAD

**Issue by PeJeWe** [nopnop2002/esp-idf-nrf905#2]
Hello i only have the  "Communication polarity (As the sender)  --->" setting, in the "Application Configuration" section.
Am i missing something?

I can't find the wifi and mqtt settings

**Comment by nopnop2002** [comment]
```
git clone https://github.com/nopnop2002/esp-idf-nrf905
cd cd esp-idf-nrf905/mqtt/
idf.py set-target {esp32/esp32s2/esp32s3/esp32c2/esp32c3/esp32c6}
idf.py menuconfig
```

**Comment by PeJeWe** [comment]
Of course,  now I get it. 
Thanks

**Comment by PeJeWe** [comment]
i have it working now.
i want to use this with domoticz to control a screen.
is it possible to use both mqtt in and out? to receive an transmit via mqtt?
like this:
'
menu "Radio Setting"

    config MQTT_TO_RADIO
        bool "Enable MQTT to Radio"
        default false
        help
            Enable communication from MQTT to Radio (MQTT to Radio).

    config RADIO_TO_MQTT
        bool "Enable Radio to MQTT"
        default false
        help
            Enable communication from Radio to MQTT (Radio to MQTT).

    config MQTT_BROKER
        string "MQTT Broker"
        default "broker.emqx.io"
        help
            Host name or IP address of the broker to connect to

    config BROKER_AUTHENTICATION
        bool "Server requests for password when connecting"
        default false
        help
            Server requests for password when connecting.

    config AUTHENTICATION_USERNAME
        depends on BROKER_AUTHENTICATION
        string "Username used for connecting to the broker"
        default "user"
        help
            Username used for connecting to the broker.

    config AUTHENTICATION_PASSWORD
        depends on BROKER_AUTHENTICATION
        string "Password used for connecting to the broker"
        default "password"
        help
            Password used for connecting to the broker.

    config MQTT_PUB_TOPIC
        depends on RADIO_TO_MQTT
        string "Publish Topic"
        default "/domoticz/in"
        help
            Topic of publish

    config MQTT_SUB_TOPIC
        depends on MQTT_TO_RADIO
        string "Subscribe Topic"
        default "/domoticz/out"
        help
            Topic of subscribe

endmenu
'

**Comment by nopnop2002** [comment]
This is possible by combining the mqtt sample code with the PingPong sample code.

Please crack the source code and challenge yourself.

Please note that nRF905 is half-duplex.
